# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time Oh My Zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="devcontainers"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME="devcontainers"
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch $(uname -m)"

# Set personal aliases, overriding those provided by Oh My Zsh libs,
# plugins, and themes. Aliases can be placed here, though Oh My Zsh
# users are encouraged to define aliases within a top-level file in
# the $ZSH_CUSTOM folder, with .zsh extension. Examples:
# - $ZSH_CUSTOM/aliases.zsh
# - $ZSH_CUSTOM/macos.zsh
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
DISABLE_AUTO_UPDATE=true
DISABLE_UPDATE_PROMPT=true
export FORCE_COLOR=1  # Enable colored output for ansible-lint and other tools

# Essential Aliases
alias ll='ls -alF'             # Long listing with file types
alias la='ls -A'               # All files except . and ..
alias l='ls -CF'               # Compact listing with file types
alias grep='grep --color=auto' # Colorized grep output
alias ls='ls --color=auto'     # Colorized ls output

# Disable pagers for better agent interaction
export SYSTEMD_PAGER=''                  # Disable pager for systemctl
export PAGER='cat'                       # Use cat instead of less/more
export MANPAGER='cat'                    # Use cat for manual pages
alias systemctl='systemctl --no-pager'   # Force systemctl to not use pager
alias journalctl='journalctl --no-pager' # Force journalctl to not use pager

# 1Password integration - only for non-vscode users
export SSH_AUTH_SOCK=~/.1password/agent.sock
export OP_BIOMETRIC_UNLOCK_ENABLED=true

# Conditional Loading
# Load additional configurations if they exist
[[ -f ~/.zsh_aliases ]] && source ~/.zsh_aliases
[[ -f ~/.zsh_local ]] && source ~/.zsh_local

if [[ $(whoami) == "vscode" ]]; then
    export ZSH="$HOME/.oh-my-zsh"
    ZSH_THEME="devcontainers"
    plugins=(git)
    source $ZSH/oh-my-zsh.sh
    DISABLE_AUTO_UPDATE=true
    DISABLE_UPDATE_PROMPT=true
    export FORCE_COLOR=1
else
    # Editor Configuration
    export EDITOR=nvim # Use neovim as default editor

    # Created by `pipx` on 2025-06-16 12:33:17
    export PATH="$PATH:/home/pbjorklund/.local/bin"
    . "$HOME/.cargo/env"
    export PATH="$HOME/.cargo/bin:$PATH"

    # Disable crash reporting
    export GNOME_DISABLE_CRASH_DIALOG=1

    # Reduce information leakage
    umask 077 # Restrictive file permissions by default

    # Secure temporary files
    export TMPDIR="/tmp/$(whoami)"
    mkdir -p "$TMPDIR"
    chmod 700 "$TMPDIR"

    # npm configuration - use home directory for global packages to avoid permissions issues
    export NPM_CONFIG_PREFIX=~/.npm-global
    export PATH=~/.npm-global/bin:$PATH

    # GitHub token function - only loads when needed
    gh_token() {
        if [ -z "$GH_TOKEN" ]; then
            export GH_TOKEN=$(op item get "GitHub Personal Access Token" --fields credential --reveal 2>/dev/null)
        fi
        echo "$GH_TOKEN"
    }

    # SSH wrapper to handle terminal compatibility
    ssh() {
        # If current TERM is kitty-based, use xterm-256color for SSH
        if [[ "$TERM" == *"kitty"* ]]; then
            env TERM=xterm-256color command ssh "$@"
        else
            command ssh "$@"
        fi
    }

    # opencode
    export PATH=/home/pbjorklund/.opencode/bin:$PATH

fi