---
- name: Setup Base Fedora System
  hosts: localhost
  connection: local
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER }}"

  tasks:
    - name: Update all packages to latest
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_only: true

    - name: Install essential system packages
      ansible.builtin.dnf:
        name:
          - curl # HTTP client
          - wget # File downloader
          - unzip # Archive extraction
          - git # Version control
          - git-credential-libsecret # Secure Git credential storage
          - openssh-clients # SSH tools (includes ssh-keygen)
          - cifs-utils # SMB/CIFS mounting utilities
        state: present

    - name: Install Python development packages
      ansible.builtin.dnf:
        name:
          - python3-pip # Python package manager
          - python3-psutil # Python system utilities (required for dconf)
        state: present

    - name: Install build tools
      ansible.builtin.dnf:
        name:
          - gcc # C compiler
          - make # Build tool
          - kernel-devel # Kernel development headers
          - kernel-headers # Kernel headers
          - dkms # Dynamic Kernel Module Support
        state: present

    - name: Start and enable essential services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - systemd-resolved
        - NetworkManager

    - name: Create standard mount directories
      ansible.builtin.file:
        path: "/mnt/{{ item }}"
        state: directory
        mode: "0755"
        owner: root
        group: root
      loop:
        - backups
        - media
        - pictures
        - external
