---
# Bluetooth Management Setup for Hyprland
# Installs BlueZ stack, GUI management tools, and configures integration

- name: "Configure Bluetooth Management"
  hosts: localhost
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    user_home: "/home/{{ original_user }}"

  tasks:
    # Core Bluetooth stack
    - name: "Install BlueZ Bluetooth stack"
      ansible.builtin.dnf:
        name:
          - bluez # Core Bluetooth protocol stack
          - bluez-tools # Additional command-line tools
          - bluez-obexd # Object Exchange daemon for file transfers
        state: present

    # GUI management tools
    - name: "Install Bluetooth GUI management tools"
      ansible.builtin.dnf:
        name:
          - blueman # Bluetooth manager with system tray
          - gnome-bluetooth # GNOME Bluetooth tools and libraries
        state: present

    # Audio codec support for high-quality Bluetooth audio
    - name: "Install Bluetooth audio codecs"
      ansible.builtin.dnf:
        name:
          - pipewire-codec-aptx # aptX codec support
        state: present
      ignore_errors: true # aptX may not be available in all repos

    # Enable and start Bluetooth service
    - name: "Enable and start Bluetooth service"
      ansible.builtin.systemd:
        name: bluetooth
        enabled: true
        state: started

    # Configure Bluetooth for better compatibility
    - name: "Configure Bluetooth main settings"
      ansible.builtin.lineinfile:
        path: /etc/bluetooth/main.conf
        regexp: "^#?{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        backup: true
      loop:
        - { key: "AutoEnable", value: "true" }
        - { key: "FastConnectable", value: "true" }
        - { key: "DiscoverableTimeout", value: "0" }
        - { key: "PairableTimeout", value: "0" }
      notify: restart bluetooth

    # Enable experimental features for better device support
    - name: "Enable Bluetooth experimental features"
      ansible.builtin.lineinfile:
        path: /etc/bluetooth/main.conf
        regexp: "^#?Experimental="
        line: "Experimental=true"
        backup: true
      notify: restart bluetooth

    # Configure audio settings for Bluetooth
    - name: "Configure Bluetooth audio settings"
      ansible.builtin.lineinfile:
        path: /etc/bluetooth/main.conf
        regexp: "^#?{{ item.key }}="
        line: "{{ item.key }}={{ item.value }}"
        backup: true
      loop:
        - { key: "MultiProfile", value: "multiple" }
        - { key: "ReconnectAttempts", value: "7" }
        - { key: "ReconnectIntervals", value: "1, 2, 4, 8, 16, 32, 64" }
      notify: restart bluetooth

    # Ensure user is in bluetooth group
    - name: "Add user to bluetooth group"
      ansible.builtin.user:
        name: "{{ original_user }}"
        groups: bluetooth
        append: true

  handlers:
    - name: restart bluetooth
      ansible.builtin.systemd:
        name: bluetooth
        state: restarted
