---
# Fingerprint Authentication Configuration
# Configures fprintd and PAM integration for fingerprint authentication
# Compatible with Fedora 42

- name: Configure Fingerprint Authentication
  hosts: localhost
  connection: local
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER }}"

  tasks:
    - name: Install fingerprint authentication packages
      ansible.builtin.dnf:
        name:
          - fprintd # Fingerprint authentication daemon with client tools
          - fprintd-pam # PAM module for fingerprint authentication
          - libfprint # Fingerprint reader library
          - libfprint-devel # Development files for libfprint
        state: present

    - name: Enable and start fprintd service
      ansible.builtin.systemd:
        name: fprintd
        enabled: true
        state: started

    - name: Configure fingerprint authentication for sudo
      ansible.builtin.lineinfile:
        path: /etc/pam.d/sudo
        line: "auth      sufficient   pam_fprintd.so"
        insertafter: "^#%PAM-1.0"
        backup: true

    - name: Configure fingerprint authentication for login
      ansible.builtin.lineinfile:
        path: /etc/pam.d/login
        line: "auth      sufficient   pam_fprintd.so"
        insertafter: "auth\\s+include\\s+system-auth"
        backup: true

    - name: Check if polkit PAM configuration exists
      ansible.builtin.stat:
        path: /etc/pam.d/polkit-1
      register: polkit_pam_stat

    - name: Configure fingerprint authentication for polkit
      ansible.builtin.lineinfile:
        path: /etc/pam.d/polkit-1
        line: "auth      sufficient   pam_fprintd.so"
        insertafter: "auth\\s+include\\s+system-auth"
        backup: true
      when: polkit_pam_stat.stat.exists

    - name: Configure hyprlock PAM for fingerprint or password authentication
      ansible.builtin.copy:
        dest: /etc/pam.d/hyprlock
        backup: true
        content: |
          # PAM configuration for hyprlock screen locker
          # Simple password-only config since fingerprint is handled by hyprlock directly

          auth        sufficient   pam_unix.so
          auth        required     pam_deny.so

          account     required     pam_unix.so

          session     required     pam_unix.so

    - name: Display enrollment instructions
      ansible.builtin.debug:
        msg: "Fingerprint authentication configured. To enroll your fingerprint, run: fprintd-enroll {{ original_user }}"
