---
# Font Installation and Configuration Playbook
# Installs fonts and configures GNOME to use Inter for UI and Fira Code for terminals
- name: Install and Configure Fonts for GNOME
  hosts: localhost
  connection: local
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER }}"

  tasks:
    # Install fonts from Fedora repositories
    - name: Install system font packages
      ansible.builtin.dnf:
        name:
          - fontconfig # Font configuration library
          - rsms-inter-fonts # Inter font family - modern UI typeface
          - fira-code-fonts # Fira Code - programming font with ligatures
          - google-noto-color-emoji-fonts # Noto Color Emoji - colored emoji support
          - google-noto-emoji-fonts # Noto Emoji - black and white emoji
          - dejavu-sans-fonts # DejaVu Sans - excellent Unicode coverage
          - dejavu-serif-fonts # DejaVu Serif - serif font family
          - dejavu-sans-mono-fonts # DejaVu Sans Mono - monospace coding font
          - liberation-fonts-common # Liberation fonts common files
          - liberation-sans-fonts # Liberation Sans - Arial alternative
          - liberation-serif-fonts # Liberation Serif - Times New Roman alternative
          - liberation-mono-fonts # Liberation Mono - Courier New alternative
          - abattis-cantarell-fonts # Cantarell - GNOME default UI font
        state: present

    # Install Nerd Fonts for waybar and terminal icons
    - name: Create fonts directory
      ansible.builtin.file:
        path: "/home/{{ original_user }}/.local/share/fonts"
        state: directory
        owner: "{{ original_user }}"
        group: "{{ original_user }}"
        mode: "0755"

    - name: Download Fira Code Nerd Font
      ansible.builtin.get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/FiraCode.zip"
        dest: "/tmp/FiraCode.zip"
        mode: "0644"

    - name: Download JetBrains Mono Nerd Font
      ansible.builtin.get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.1.1/JetBrainsMono.zip"
        dest: "/tmp/JetBrainsMono.zip"
        mode: "0644"

    - name: Extract Fira Code Nerd Font
      ansible.builtin.unarchive:
        src: "/tmp/FiraCode.zip"
        dest: "/home/{{ original_user }}/.local/share/fonts"
        owner: "{{ original_user }}"
        group: "{{ original_user }}"
        remote_src: true

    - name: Extract JetBrains Mono Nerd Font
      ansible.builtin.unarchive:
        src: "/tmp/JetBrainsMono.zip"
        dest: "/home/{{ original_user }}/.local/share/fonts"
        owner: "{{ original_user }}"
        group: "{{ original_user }}"
        remote_src: true

    - name: Clean up font archives
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - "/tmp/FiraCode.zip"
        - "/tmp/JetBrainsMono.zip"

    # Update font cache for immediate availability
    - name: Update font cache
      ansible.builtin.command:
        cmd: fc-cache -fv
      become: true
      become_user: "{{ original_user }}"
      changed_when: true

    # Configure GNOME to use Inter for UI and Fira Code for monospace
    - name: Set Inter as default interface font
      community.general.dconf:
        key: "/org/gnome/desktop/interface/font-name"
        value: "'Inter 11'"
      become: true
      become_user: "{{ original_user }}"

    - name: Set Inter as default document font
      community.general.dconf:
        key: "/org/gnome/desktop/interface/document-font-name"
        value: "'Inter 11'"
      become: true
      become_user: "{{ original_user }}"

    - name: Set Fira Code as default monospace font
      community.general.dconf:
        key: "/org/gnome/desktop/interface/monospace-font-name"
        value: "'Fira Code 10'"
      become: true
      become_user: "{{ original_user }}"

    - name: Set Inter as window title font
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/titlebar-font"
        value: "'Inter Bold 11'"
      become: true
      become_user: "{{ original_user }}"

    # Display installation completion
    - name: Display font installation completion
      ansible.builtin.debug:
        msg: |
          Font installation and configuration complete for GNOME on Fedora!

          Installed font families:
          - Inter - Modern UI typeface designed for computer screens
          - Fira Code - Programming font with ligatures
          - Fira Code Nerd Font - Programming font with icons and symbols
          - JetBrains Mono Nerd Font - Programming font with icons and symbols
          - Noto Emoji - Google's comprehensive emoji support
          - DejaVu (Sans, Serif, Mono) - Excellent Unicode coverage
          - Liberation (Sans, Serif, Mono) - Metric-compatible alternatives
          - Cantarell - GNOME's default UI font

          GNOME font configuration applied:
          - Interface font: Inter 11
          - Document font: Inter 11
          - Monospace font: Fira Code 10 (terminals, IDEs)
          - Window title font: Inter Bold 11

          These settings are active immediately. You can adjust font sizes in
          GNOME Settings > Appearance > Fonts if needed.
          Configure default fonts in GNOME Settings > Appearance > Fonts.
