---
# Hyprland Desktop Environment Setup
# Installs packages and configures system-level settings for Hyprland
# NOTE: Dotfiles are deployed separately using dotfiles/install.sh

- name: "Configure Hyprland Desktop Environment"
  hosts: localhost
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    user_home: "/home/{{ original_user }}"

  tasks:
    # Core Hyprland packages from main Fedora repository
    - name: "Install Hyprland core packages"
      ansible.builtin.dnf:
        name:
          - hyprland # Tiling window manager (includes hyprctl)
          - hyprutils # Hyprland utilities library
          - xdg-desktop-portal-hyprland # Desktop portal for Hyprland
        state: present

    # Hyprland-specific tools
    - name: "Install Hyprland-specific packages"
      ansible.builtin.dnf:
        name:
          - swaybg # Wallpaper daemon for Wayland compositors
          - wofi # Application launcher
          - mako # Notification daemon
          - swaylock # Screen locker
          - hypridle # Idle management daemon for Hyprland
          - grim # Screenshot tool
          - slurp # Selection tool for screenshots
          - wf-recorder # Screen recording tool
          - jq # JSON processor for wallpaper management script
          - inotify-tools # File system event monitoring for waybar auto-restart
        state: present

    # Configure GDM for Wayland (if using GDM)
    - name: "Check if GDM is installed and enabled"
      ansible.builtin.systemd:
        name: gdm
      register: gdm_status
      failed_when: false
      changed_when: false

    - name: "Enable Wayland in GDM"
      ansible.builtin.lineinfile:
        path: /etc/gdm/custom.conf
        regexp: "^#?WaylandEnable="
        line: "WaylandEnable=true"
        backup: true
      when: gdm_status.status.LoadState is defined and gdm_status.status.LoadState == "loaded"

    # Create desktop entry for Hyprland
    - name: "Create Hyprland desktop entry"
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Name=Hyprland
          Comment=A dynamic tiling Wayland compositor
          Exec=Hyprland
          Type=Application
          DesktopNames=Hyprland
        dest: /usr/share/wayland-sessions/hyprland.desktop
        owner: root
        group: root
        mode: "0644"

- name: "Import common Wayland desktop environment"
  import_playbook: wayland-desktop.ansible.yml
