---
- name: Configure Personal Settings
  hosts: localhost
  connection: local
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER }}"

  tasks:
    # GNOME Configuration
    - name: Enable focus-on-hover in GNOME
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/focus-mode"
        value: "'sloppy'"
      become: true
      become_user: "{{ original_user }}"

    - name: Remap Caps Lock to Ctrl
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:ctrl_modifier']"
      become: true
      become_user: "{{ original_user }}"

    - name: Configure Dash to Dock - disable auto-hide
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/autohide"
        value: "false"
      become: true
      become_user: "{{ original_user }}"

    - name: Configure Dash to Dock - windows above dock
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
        value: "false"
      become: true
      become_user: "{{ original_user }}"

    - name: Enable night light
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
        value: "true"
      become: true
      become_user: "{{ original_user }}"

    - name: Set night light temperature
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
        value: "uint32 4000"
      become: true
      become_user: "{{ original_user }}"

    # Note: Power management is now handled by Hyprland via swayidle
    # See dotfiles/.config/hypr/conf/power.conf for idle/sleep configuration
