---
- name: Configure Personal Settings
  hosts: localhost
  connection: local
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER }}"

  tasks:
    # GNOME Configuration
    - name: Enable focus-on-hover in GNOME
      community.general.dconf:
        key: "/org/gnome/desktop/wm/preferences/focus-mode"
        value: "'sloppy'"
      become: true
      become_user: "{{ original_user }}"

    - name: Remap Caps Lock to Ctrl
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/xkb-options"
        value: "['caps:ctrl_modifier']"
      become: true
      become_user: "{{ original_user }}"

    - name: Configure Dash to Dock - disable auto-hide
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/autohide"
        value: "false"
      become: true
      become_user: "{{ original_user }}"

    - name: Configure Dash to Dock - windows above dock
      community.general.dconf:
        key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
        value: "false"
      become: true
      become_user: "{{ original_user }}"

    - name: Enable night light
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/color/night-light-enabled"
        value: "true"
      become: true
      become_user: "{{ original_user }}"

    - name: Set night light temperature
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/color/night-light-temperature"
        value: "uint32 4000"
      become: true
      become_user: "{{ original_user }}"

    - name: Configure power settings - never suspend on AC
      community.general.dconf:
        key: "/org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type"
        value: "'nothing'"
      become: true
      become_user: "{{ original_user }}"

    - name: Display SSH public key for GitHub
      ansible.builtin.command:
        cmd: cat /home/{{ original_user }}/.ssh/id_ed25519.pub
      register: ssh_public_key
      become: true
      become_user: "{{ original_user }}"
      changed_when: false
      failed_when: false

    - name: Show SSH public key message
      ansible.builtin.debug:
        msg: "🔑 SSH Key Ready: Add this public key to GitHub - {{ ssh_public_key.stdout | default('SSH key not found - run base-system.ansible.yml first') }}"
      when: ssh_public_key.rc == 0
