---
- name: Configure System Services
  hosts: localhost
  connection: local
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER }}"

  tasks:
    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: true

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ original_user }}"
        groups: docker
        append: true

    - name: Display Docker configuration message
      ansible.builtin.debug:
        msg: |
          ✅ Docker has been configured and user added to docker group.

          ⚠️  IMPORTANT: You need to log out and log back in for group membership to take effect.
          Until you do this, you'll need to use 'sudo docker' commands.

          After logging back in, 'docker ps' will work without sudo.
