---
# TUIgreet Display Manager Setup for Hyprland
# WARNING: This is a downgrade from SDDM - provides text-only interface
# Installs TUIgreet with greetd daemon for session selection
# NOTE: Consider using SDDM instead for better user experience

- name: TUIgreet Display Manager Configuration
  hosts: localhost
  become: true
  vars:
    greetd_config_dir: "/etc/greetd"

  tasks:
    - name: Check if GDM is installed and enabled
      ansible.builtin.systemd:
        name: gdm
      register: gdm_status
      failed_when: false

    - name: Check if SDDM is installed and enabled
      ansible.builtin.systemd:
        name: sddm
      register: sddm_status
      failed_when: false

    - name: Install greetd daemon and TUIgreet
      ansible.builtin.dnf:
        name:
          - greetd # Greet daemon for login management
          - tuigreet # TUI greeter for greetd
        state: present

    - name: Create greeter user for greetd
      ansible.builtin.user:
        name: greeter
        system: true
        shell: /sbin/nologin
        home: /var/lib/greeter
        create_home: false
        comment: "Greeter user for greetd"

    - name: Remove current display-manager.service symlink
      ansible.builtin.file:
        path: /etc/systemd/system/display-manager.service
        state: absent

    - name: Enable greetd as display manager
      ansible.builtin.systemd:
        name: greetd
        enabled: true
        daemon_reload: true

    - name: Create display-manager.service symlink to greetd
      ansible.builtin.file:
        src: /usr/lib/systemd/system/greetd.service
        dest: /etc/systemd/system/display-manager.service
        state: link
