---
# Common packages for Wayland-based desktop environments

- name: "Configure Common Wayland Desktop Environment"
  hosts: localhost
  become: true
  vars:
    original_user: "{{ ansible_env.SUDO_USER | default(ansible_user_id) }}"
    user_home: "/home/{{ original_user }}"

  tasks:
    # Common Wayland tools
    - name: "Install common Wayland packages"
      ansible.builtin.dnf:
        name:
          - waybar # Status bar for Wayland
          - wl-clipboard # Clipboard utilities for Wayland
          - brightnessctl # Brightness control
          - playerctl # Media player control
          - pavucontrol # Audio control GUI
          - network-manager-applet # Network management applet
        state: present

    # Audio system
    - name: "Install audio system packages"
      ansible.builtin.dnf:
        name:
          - pipewire # Modern audio system
          - pipewire-alsa # ALSA compatibility
          - pipewire-pulseaudio # PulseAudio compatibility
          - wireplumber # Session manager for PipeWire
          - alsa-utils # ALSA utilities
        state: present

    # Fonts for better UI rendering
    - name: "Install essential fonts"
      ansible.builtin.dnf:
        name:
          - fontawesome-fonts # Icon fonts
          - google-noto-emoji-fonts # Emoji support
          - google-noto-sans-fonts # Unicode font coverage
          - liberation-fonts-all # Free alternatives to Times, Arial, Courier
          - dejavu-fonts-all # High-quality fonts
        state: present

    # Terminal and utilities
    - name: "Install terminal and utilities"
      ansible.builtin.dnf:
        name:
          - kitty # Modern GPU-accelerated terminal
          - dolphin # File manager
        state: present

    # Enable required services
    - name: "Enable PipeWire services for current user"
      ansible.builtin.systemd:
        name: "{{ item }}"
        enabled: true
        scope: user
        daemon_reload: true
      loop:
        - pipewire.service
        - pipewire-pulse.service
        - wireplumber.service
      become: false
      become_user: "{{ original_user }}"
