# Complete Fedora Workstation Setup - orchestrates all component playbooks

- name: Run base system setup
  import_playbook: base-system.ansible.yml
  tags: base

- name: Configure security and authentication
  import_playbook: security-authentication.ansible.yml
  tags: security

- name: Install development tools
  import_playbook: development-tools.ansible.yml
  tags: development

- name: Install desktop applications
  import_playbook: desktop-applications.ansible.yml
  tags: desktop

- name: Configure services
  import_playbook: services.ansible.yml
  tags: services

- name: Deploy personal dotfiles
  import_playbook: dotfiles.ansible.yml
  tags: dotfiles

- name: Apply personal configuration
  import_playbook: personal-config.ansible.yml
  tags: config

- name: Configure Hyprland desktop environment
  import_playbook: hyprland-desktop.ansible.yml
  tags: hyprland

- name: Configure Niri desktop environment
  import_playbook: niri-desktop.ansible.yml
  tags: niri

- name: Configure local DNS
  import_playbook: configure-local-dns.ansible.yml
  tags: dns

- name: Install DisplayLink drivers
  import_playbook: hardware-displaylink.ansible.yml
  tags: displaylink

- name: Configure NAS storage
  import_playbook: storage-nas.ansible.yml
  tags: nas

- name: Configure backup system
  import_playbook: backup-system.ansible.yml
  tags: backup

- name: Configure firewall and security
  import_playbook: firewall-security.ansible.yml
  tags: security

- name: Apply privacy hardening
  import_playbook: privacy-hardening.ansible.yml
  tags: privacy

- name: Configure fingerprint authentication
  import_playbook: fingerprint-auth.ansible.yml
  tags: fingerprint

- name: Display setup completion summary
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Display setup completion summary
      ansible.builtin.debug:
        msg: "🎉 Fedora Workstation Setup Complete! Security & Privacy features applied. Next: Reboot, then run dotfiles/install.sh for personal configs"
      tags: always
