# Complete Fedora Workstation Setup - orchestrates all component playbooks

- name: Run base system setup
  import_playbook: base-system.ansible.yml
  tags: base

- name: Install applications
  import_playbook: applications.ansible.yml
  tags: apps

- name: Configure services
  import_playbook: services.ansible.yml
  tags: services

- name: Apply personal configuration
  import_playbook: personal-config.ansible.yml
  tags: config

- name: Configure Hyprland desktop environment
  import_playbook: hyprland-desktop.ansible.yml
  tags: hyprland

- name: Configure local DNS (optional)
  import_playbook: configure-local-dns.ansible.yml
  tags: dns
  when: configure_dns | default(false)

- name: Install DisplayLink drivers (optional)
  import_playbook: hardware-displaylink.ansible.yml
  tags: displaylink
  when: install_displaylink | default(false)

- name: Configure NAS storage (optional)
  import_playbook: storage-nas.ansible.yml
  tags: nas
  when: configure_nas | default(false)

- name: Configure backup system
  import_playbook: backup-system.ansible.yml
  tags: backup

- name: Configure firewall and security
  import_playbook: firewall-security.ansible.yml
  tags: security

- name: Apply privacy hardening
  import_playbook: privacy-hardening.ansible.yml
  tags: privacy

- name: Configure fingerprint authentication (optional)
  import_playbook: fingerprint-auth.ansible.yml
  tags: fingerprint
  when: configure_fingerprint | default(false)

- name: Display setup completion summary
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Display setup completion summary
      ansible.builtin.debug:
        msg: |
          🎉 Fedora Workstation Setup Complete!

          🔒 Security & Privacy Features Applied:
          • Firewall enabled with intrusion detection (fail2ban)
          • Privacy-focused DNS with DNS-over-TLS
          • SSH hardened with strong ciphers
          • Git credentials secured with libsecret
          • Rootless containers (Podman) for development
          • Privacy-invasive services disabled
          • System hardening with kernel security parameters

          📋 Next Steps:
          1. Reboot to ensure all services start properly
          2. Install dotfiles: cd dotfiles && ./install.sh
          3. Configure VS Code for devcontainer compatibility
          4. Test container functionality: podman run hello-world

          🔐 Security Notes:
          • Your system uses modern, secure defaults
          • Container access is rootless (no docker group risk)
          • Location services and tracking disabled
          • Check security warnings in ~/.container-security-info
      tags: always
